nohup: ignoring input
Hostname bagration not defined in /conf/study_paths/study_paths.yaml. Using default paths.
[1mParser[0m Injecting argv ['model=clip_cnntransformer', 'dset.selections=["gwilliams2022"]', 'dset.bandpass=true', 'dset.bandpass_high=0.1', 'dset.bandpass_lower=40.0', 'seed=2037', 'is_sound=true'] from sig c97c100b
{'wandb': {'use_wandb': True, 'project': 'brainmagick', 'group': 'brainmagick-group'}, 'num_prints': 5, 'device': 'cuda:1', 'verbose': 0, 'show': 0, 'download_only': False, 'is_sound': True, 'slurm': {'mem_per_gpu': 100, 'time': 4320}, 'continue_sig': None, 'continue_best': True, 'seed': 2037, 'dummy': None, 'cache': './cache', 'features_models': './features_models', 'early_stop_patience': 10, 'eval_every': 1, 'eval_train_set': False, 'optim': {'name': 'adam', 'shuffle': False, 'lr': 0.0003, 'beta2': 0.999, 'eps': 1e-08, 'epochs': 200, 'batch_size': 256, 'loss': 'clip', 'weight_decay': 0.0, 'use_weighting': False, 'max_batches': 1200, 'svd': 0.0, 'negatives': None, 'negative_pool_size': None, 'scheduler': {'name': 'None'}}, 'clip': {'linear': None, 'twin': True, 'pool': False, 'tmin': None, 'tmax': None, 'tmin_train': None, 'tmax_train': None, 'center': False, 'probabilities': False}, 'test': {'wer_negatives': 10000, 'wer_topx': 10, 'wer_random': False, 'wer_recordings': 40, 'wer_study': None}, 'dset': {'selections': ['gwilliams2022'], 'tmin': -0.5, 'tmax': 2.5, 'n_recordings': 1000, 'n_subjects': None, 'n_subjects_test': None, 'shuffle_recordings_seed': -1, 'skip_recordings': 0, 'test_ratio': 0.2, 'valid_ratio': 0.1, 'remove_ratio': 0.0, 'condition': 0.5, 'apply_baseline': True, 'min_block_duration': 6, 'force_uid_assignement': False, 'min_n_blocks_per_split': 1, 'ignore_end_in_block': False, 'ignore_start_in_block': False, 'sample_rate': 120, 'highpass': 0, 'bandpass': True, 'bandpass_high': 0.1, 'bandpass_lower': 40.0, 'event_mask': True, 'split_wav_as_block': True, 'allow_empty_split': False, 'autoreject': False, 'test': {'tmin': None, 'tmax': None, 'condition': 'word'}, 'features': ['Wav2VecTransformer'], 'extra_test_features': [], 'features_params': {'MelSpectrum': {'n_fft': 512, 'n_mels': 120, 'normalized': True, 'use_log_scale': True, 'log_scale_eps': 1e-05}, 'Pitch': {'min_f0': 100, 'max_f0': 350}, 'WordHash': {'buckets': 100000}, 'XlmEmbedding': {'contextual': False}, 'WordEmbedding': {'lang': 'auto'}, 'WordEmbeddingSmall': {'lang': 'auto'}, 'PartOfSpeech': {'lang': 'auto'}, 'Wav2VecTransformer': {'layers': [14, 15, 16, 17, 18], 'device': 'cpu', 'random': False, 'is_interpolate': True, 'size': 150}, 'Wav2VecChunk': {'device': 'cpu'}}}, 'override_n_subjects_model': None, 'norm': {'scaler': {'per_channel': False, 'n_samples_per_recording': 200, 'n_samples_features': 8000}, 'max_scale': 20.0, 'clip': True, 'exclude_empty_features': False}, 'task': {'type': 'decode', 'meg_init': 0.3, 'lowpass': 0, 'offset_meg_ms': 150, 'lowpass_gt': True, 'lowpass_gt_test': False, 'mask_loss': False}, 'dora': {'dir': './outputs', 'exclude': ['wandb.*', 'num_prints', 'device', 'num_workers', 'verbose', 'cache', 'features_models'], 'git_save': True}, 'model_name': 'cnntransformer', 'convrnn': {'concatenate': False, 'depth': 2, 'linear_out': False, 'complex_out': False, 'kernel_size': 4, 'stride': 2, 'growth': 1.0, 'lstm': 4, 'bidirectional_lstm': False, 'flip_lstm': False, 'attention': 0, 'heads': 4, 'conv_dropout': 0.0, 'lstm_dropout': 0.0, 'dropout_input': 0.0, 'batch_norm': False, 'relu_leakiness': 0.0, 'subject_dim': 64, 'embedding_location': ['lstm'], 'embedding_scale': 1.0, 'subject_layers': False, 'subject_layers_dim': 'input'}, 'simpleconv': {'concatenate': False, 'depth': 4, 'linear_out': False, 'complex_out': False, 'dilation_growth': 2, 'dilation_period': None, 'skip': False, 'post_skip': False, 'growth': 1.0, 'scale': None, 'rewrite': False, 'groups': 1, 'glu': 0, 'glu_context': 0, 'glu_glu': True, 'gelu': False, 'dual_path': 0, 'conv_dropout': 0.0, 'dropout_input': 0.0, 'batch_norm': False, 'relu_leakiness': 0.0, 'subject_dim': 64, 'subject_layers': False, 'embedding_scale': 1.0, 'subject_layers_dim': 'input', 'subject_layers_id': False, 'n_fft': None, 'fft_complex': True, 'merger': False, 'merger_pos_dim': 256, 'merger_channels': 270, 'merger_dropout': 0.2, 'merger_penalty': 0.0, 'merger_per_subject': False, 'dropout': 0.0, 'dropout_rescale': True, 'initial_linear': 0, 'initial_depth': 1, 'initial_nonlin': False, 'avg_pool_out': False, 'adaptive_pooling_size': '1,', 'flatten_out_channels': 512, 'strides': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'kernel_size': [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], 'padding': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'seq_len': -1, 'auto_padding': True, 'is_deformable_conv': False}, 'simpletransformer': {'hidden': {'meg': 320}, 'depth': 4, 'nhead': 8, 'subject_layers': False, 'positional_embedding': False, 'merger': False, 'merger_pos_dim': 2048, 'merger_channels': 272, 'model_type': 'basic', 'dim_ff': 2048, 'attention_window': [32, 32, 32, 32]}, 'timesnet': {'hidden': {'meg': 320}, 'depth': 2, 'subject_layers': False, 'sequence_lenth': 361, 'num_kernels': 6, 'top_k': 3, 'dropout_projection': 0.3, 'd_model': 32, 'd_ff': 32, 'flatten_out_channels': 1024, 'merger': False, 'merger_pos_dim': 2048, 'merger_channels': 270, 'enc_embedding': True}, 'cnntransformer': {'hidden': {'meg': 320}, 'batch_norm': True, 'depth': 4, 'dilation_period': 4, 'skip': True, 'subject_layers': True, 'subject_dim': 0, 'complex_out': True, 'glu': 2, 'glu_context': 1, 'merger': True, 'initial_linear': 270, 'gelu': True, 'merger_pos_dim': 2048, 'avg_pool_out': False, 'adaptive_pooling_size': 1, 'flatten_out': True, 'flatten_out_channels': 264, 'strides': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'conv_dropout': 0.0, 'kernel_size': [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], 'padding': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'seq_len': 361, 'auto_padding': True, 'is_deformable_conv': False, 'in_channels_tranformer': 264, 'out_channels_transformer': 1024, 'dim_ff': 2048, 'nhead': 8, 'positional_embedding': 'False,', 'positional_embedding_dropout': 0.0, 'depth_transformer': 2}, 'num_workers': 5, 'feature_model_name': None, 'selections': {'audio_mous': {'study': 'schoffelen2019', 'modality': 'audio', 'events_filter': None}, 'audio_mous_wl': {'study': 'schoffelen2019', 'modality': 'audio', 'events_filter': 'condition == "word_list"'}, 'visual_mous': {'study': 'schoffelen2019', 'modality': 'visual', 'events_filter': None}, 'gwilliams2022': {'study': 'gwilliams2022'}, 'broderick2019': {'study': 'broderick2019'}, 'fake': {'study': 'fake'}, 'brennan2019': {'study': 'brennan2019'}}, 'study_paths': {'default': {'gwilliams2022': './data/gwilliams2022/', 'schoffelen2019': './data/schoffelen2019/', 'brennan2019': './data/brennan2019/', 'broderick2019': './data/broderick2019/'}}}
[2024-02-28 19:06:45,674][bm._env][WARNING] - Hostname bagration not defined in /conf/study_paths/study_paths.yaml. Using default paths.
[2024-02-28 19:06:45,704][bm.train][INFO] - For logs, checkpoints and samples, check /home/zubrikhina/brainmagick_MICCAI/outputs/xps/c97c100b.
[2024-02-28 19:06:45,705][bm.train][INFO] - Caching intermediate data under /home/zubrikhina/brainmagick_MICCAI/cache.
/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
[[36m02-28 19:06:45[0m][[34mdora.distrib[0m][[32mINFO[0m] - world_size is 1, skipping init.[0m
[[36m02-28 19:06:45[0m][[34mbm.dataset[0m][[33mWARNING[0m] - Requested 1000 recordings but only found 196[0m
[[36m02-28 19:07:30[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 1/196.[0m
[[36m02-28 19:07:32[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 2/196.[0m
[[36m02-28 19:07:49[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 5/196.[0m
[[36m02-28 19:07:55[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 6/196.[0m
[[36m02-28 19:08:09[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 9/196.[0m
[[36m02-28 19:08:10[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 10/196.[0m
[[36m02-28 19:08:23[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 13/196.[0m
[[36m02-28 19:08:24[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 14/196.[0m
[[36m02-28 19:08:33[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 17/196.[0m
[[36m02-28 19:08:34[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 18/196.[0m
[[36m02-28 19:08:43[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 21/196.[0m
[[36m02-28 19:08:45[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 22/196.[0m
[[36m02-28 19:08:56[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 25/196.[0m
[[36m02-28 19:08:58[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 26/196.[0m
[[36m02-28 19:09:09[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 29/196.[0m
[[36m02-28 19:09:10[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 30/196.[0m
[[36m02-28 19:09:20[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 33/196.[0m
[[36m02-28 19:09:22[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 34/196.[0m
[[36m02-28 19:09:30[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 37/196.[0m
[[36m02-28 19:09:31[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 38/196.[0m
[[36m02-28 19:09:40[0m][[34mbm.dataset[0m][[32mINFO[0m] - Loading Subjects | 39/196 | 0.31 it/sec[0m
[[36m02-28 19:09:40[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 41/196.[0m
[[36m02-28 19:09:42[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 42/196.[0m
[[36m02-28 19:09:54[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 45/196.[0m
[[36m02-28 19:09:56[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 46/196.[0m
[[36m02-28 19:10:07[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 49/196.[0m
[[36m02-28 19:10:09[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 50/196.[0m
[[36m02-28 19:10:18[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 53/196.[0m
[[36m02-28 19:10:20[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 54/196.[0m
[[36m02-28 19:10:28[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 57/196.[0m
[[36m02-28 19:10:29[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 58/196.[0m
[[36m02-28 19:10:37[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 61/196.[0m
[[36m02-28 19:10:38[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 62/196.[0m
[[36m02-28 19:10:49[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 65/196.[0m
[[36m02-28 19:10:50[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 66/196.[0m
[[36m02-28 19:11:02[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 69/196.[0m
[[36m02-28 19:11:03[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 70/196.[0m
[[36m02-28 19:11:15[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 73/196.[0m
[[36m02-28 19:11:17[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 74/196.[0m
[[36m02-28 19:11:29[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 77/196.[0m
[[36m02-28 19:11:31[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 78/196.[0m
[[36m02-28 19:11:36[0m][[34mbm.dataset[0m][[32mINFO[0m] - Loading Subjects | 78/196 | 0.32 it/sec[0m
[[36m02-28 19:11:43[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 81/196.[0m
[[36m02-28 19:11:45[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 82/196.[0m
[[36m02-28 19:11:56[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 85/196.[0m
[[36m02-28 19:11:58[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 86/196.[0m
[[36m02-28 19:12:09[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 89/196.[0m
[[36m02-28 19:12:11[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 90/196.[0m
[[36m02-28 19:12:22[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 93/196.[0m
[[36m02-28 19:12:24[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 94/196.[0m
[[36m02-28 19:12:36[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 97/196.[0m
[[36m02-28 19:12:37[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 98/196.[0m
[[36m02-28 19:12:50[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 101/196.[0m
[[36m02-28 19:12:51[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 102/196.[0m
[[36m02-28 19:13:03[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 105/196.[0m
[[36m02-28 19:13:05[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 106/196.[0m
[[36m02-28 19:13:16[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 109/196.[0m
[[36m02-28 19:13:18[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 110/196.[0m
[[36m02-28 19:13:29[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 113/196.[0m
[[36m02-28 19:13:31[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 114/196.[0m
[[36m02-28 19:13:42[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 117/196.[0m
[[36m02-28 19:13:44[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 118/196.[0m
[[36m02-28 19:13:45[0m][[34mbm.dataset[0m][[32mINFO[0m] - Loading Subjects | 117/196 | 0.31 it/sec[0m
[[36m02-28 19:13:56[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 121/196.[0m
[[36m02-28 19:13:57[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 122/196.[0m
[[36m02-28 19:14:09[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 125/196.[0m
[[36m02-28 19:14:10[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 126/196.[0m
[[36m02-28 19:14:22[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 129/196.[0m
[[36m02-28 19:14:23[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 130/196.[0m
[[36m02-28 19:14:35[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 133/196.[0m
[[36m02-28 19:14:37[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 134/196.[0m
[[36m02-28 19:14:48[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 137/196.[0m
[[36m02-28 19:14:49[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 138/196.[0m
[[36m02-28 19:14:58[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 141/196.[0m
[[36m02-28 19:14:59[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 142/196.[0m
[[36m02-28 19:15:07[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 145/196.[0m
[[36m02-28 19:15:08[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 146/196.[0m
[[36m02-28 19:15:16[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 149/196.[0m
[[36m02-28 19:15:17[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 150/196.[0m
[[36m02-28 19:15:29[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 153/196.[0m
[[36m02-28 19:15:30[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 154/196.[0m
[[36m02-28 19:15:41[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 157/196.[0m
[[36m02-28 19:15:41[0m][[34mbm.dataset[0m][[32mINFO[0m] - Loading Subjects | 156/196 | 0.32 it/sec[0m
[[36m02-28 19:15:42[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 158/196.[0m
[[36m02-28 19:15:53[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 161/196.[0m
[[36m02-28 19:15:55[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 162/196.[0m
[[36m02-28 19:16:05[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 165/196.[0m
[[36m02-28 19:16:06[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 166/196.[0m
[[36m02-28 19:16:16[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 169/196.[0m
[[36m02-28 19:16:17[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 170/196.[0m
[[36m02-28 19:16:24[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 173/196.[0m
[[36m02-28 19:16:25[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 174/196.[0m
[[36m02-28 19:16:33[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 177/196.[0m
[[36m02-28 19:16:33[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 178/196.[0m
[[36m02-28 19:16:42[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 181/196.[0m
[[36m02-28 19:16:43[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 182/196.[0m
[[36m02-28 19:16:53[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 185/196.[0m
[[36m02-28 19:16:55[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 186/196.[0m
[[36m02-28 19:17:05[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 189/196.[0m
[[36m02-28 19:17:06[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 190/196.[0m
[[36m02-28 19:17:15[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 193/196.[0m
[[36m02-28 19:17:16[0m][[34mbm.dataset[0m][[33mWARNING[0m] - No blocks found for split 2/3 of recording 194/196.[0m
[[36m02-28 19:17:25[0m][[34mbm.dataset[0m][[32mINFO[0m] - Loading Subjects | 195/196 | 0.33 it/sec[0m
[[36m02-28 19:17:25[0m][[34mbm.dataset[0m][[32mINFO[0m] - # Examples (train | valid | test): 314922 | 37249 | 55223[0m
[[36m02-28 19:17:25[0m][[34mbm.train[0m][[32mINFO[0m] - Model hash: 77748adf440528a0b4f1c8c5d923123d99e9d60d[0m
/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/flashy/loggers/tensorboard.py:47: UserWarning: tensorboard package was not found: use pip install tensorboard
  warnings.warn("tensorboard package was not found: use pip install tensorboard")
wandb: Currently logged in as: almachan2358 (gnn-neuro). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.16.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.16.1
wandb: Run data is saved locally in /home/zubrikhina/brainmagick_MICCAI/outputs/xps/c97c100b/wandb/run-20240228_191732-c97c100b
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run c97c100b
wandb: ⭐️ View project at https://wandb.ai/gnn-neuro/brainmagick
wandb: 🚀 View run at https://wandb.ai/gnn-neuro/brainmagick/runs/c97c100b
[[36m02-28 19:17:42[0m][[34mbm.solver[0m][[32mINFO[0m] - Scaler cache file /home/zubrikhina/brainmagick_MICCAI/cache/scaler/e7138f34c964e59b/bf21a9e8fbc5a384.pkl[0m
264
CNNTransformer(
  (merger): ChannelMerger(
    (embedding): FourierEmb()
  )
  (initial_linear): Sequential(
    (0): Conv1d(270, 270, kernel_size=(1,), stride=(1,))
  )
  (subject_layers): SubjectLayers(270, 270, 27)
  (final): Sequential(
    (0): Conv1d(320, 640, kernel_size=(1,), stride=(1,))
    (1): GELU(approximate='none')
    (2): ConvTranspose1d(640, 264, kernel_size=(1,), stride=(1,))
  )
  (encoders): ModuleDict(
    (meg): ConvSequence(
      (sequence): ModuleList(
        (0): Sequential(
          (0): Conv1d(270, 320, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): BatchNorm1d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): GELU(approximate='none')
        )
        (1): Sequential(
          (0): Conv1d(320, 320, kernel_size=(3,), stride=(1,), padding=(2,), dilation=(2,))
          (1): BatchNorm1d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): GELU(approximate='none')
        )
        (2): Sequential(
          (0): Conv1d(320, 320, kernel_size=(3,), stride=(1,), padding=(4,), dilation=(4,))
          (1): BatchNorm1d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): GELU(approximate='none')
        )
        (3): Sequential(
          (0): Conv1d(320, 320, kernel_size=(3,), stride=(1,), padding=(8,), dilation=(8,))
          (1): BatchNorm1d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (2): GELU(approximate='none')
        )
      )
      (glus): ModuleList(
        (0): None
        (1): Sequential(
          (0): Conv1d(320, 640, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): GLU(dim=1)
        )
        (2): None
        (3): Sequential(
          (0): Conv1d(320, 640, kernel_size=(3,), stride=(1,), padding=(1,))
          (1): GLU(dim=1)
        )
      )
    )
  )
  (positional_embedding): PositionalEncoding(
    (dropout): Dropout(p=0.0, inplace=False)
  )
  (layers): Sequential(
    (0): TransformerEncoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=264, out_features=264, bias=True)
      )
      (linear1): Linear(in_features=264, out_features=2048, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_features=2048, out_features=264, bias=True)
      (norm1): LayerNorm((264,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((264,), eps=1e-05, elementwise_affine=True)
      (dropout1): Dropout(p=0.1, inplace=False)
      (dropout2): Dropout(p=0.1, inplace=False)
    )
  )
  (last): Linear(in_features=264, out_features=1024, bias=True)
)
None
None
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-large-xlsr-53 and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[[36m02-28 19:39:28[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 1 | 240/1200 | 0.18 it/sec | loss 6.3597[0m
[[36m02-28 19:50:38[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 1 | 480/1200 | 0.24 it/sec | loss 5.0872[0m
[[36m02-28 20:00:41[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 1 | 720/1200 | 0.28 it/sec | loss 4.2944[0m
[[36m02-28 20:11:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 1 | 960/1200 | 0.30 it/sec | loss 3.8016[0m
[[36m02-28 20:21:44[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 1 | loss=3.4612 | duration=3842.0703[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-28 20:23:36[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 1 | 29/146 | 0.28 it/sec | loss 1.7985[0m
[[36m02-28 20:25:12[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 1 | 58/146 | 0.29 it/sec | loss 1.8179[0m
[[36m02-28 20:26:47[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 1 | 87/146 | 0.29 it/sec | loss 1.8369[0m
[[36m02-28 20:28:25[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 1 | 116/146 | 0.30 it/sec | loss 1.8422[0m
[[36m02-28 20:29:44[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 1 | 145/146 | 0.31 it/sec | loss 1.8338[0m
[[36m02-28 20:29:45[0m][[34mbm.solver[0m][[32mINFO[0m] - [1mNew best valid loss 1.8338[0m
[[36m02-28 20:29:45[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 1 | loss=1.8338 | duration=481.3385[0m
[[36m02-28 20:30:26[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 9/45 | 0.27 it/sec[0m
[[36m02-28 20:30:52[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 18/45 | 0.30 it/sec[0m
[[36m02-28 20:31:22[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 27/45 | 0.30 it/sec[0m
[[36m02-28 20:31:49[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 36/45 | 0.31 it/sec[0m
[[36m02-28 20:32:51[0m][[34mbm.wer[0m][[32mINFO[0m] - wer 10000 negatives selected[0m
[[36m02-28 20:34:13[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 2254/11270 | 28.38 it/sec[0m
[[36m02-28 20:35:32[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 4508/11270 | 28.54 it/sec[0m
[[36m02-28 20:36:52[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 6762/11270 | 28.38 it/sec[0m
[[36m02-28 20:38:13[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 9016/11270 | 28.24 it/sec[0m
[[36m02-28 20:39:38[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTest Summary | Epoch 1 | wer=48.740% | wer_vocab=21.517% | duration=592.3513[0m
[[36m02-28 20:39:38[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-28 20:50:30[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 2 | 240/1200 | 0.37 it/sec | loss 1.9223[0m
[[36m02-28 21:00:44[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 2 | 480/1200 | 0.38 it/sec | loss 1.8648[0m
[[36m02-28 21:09:59[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 2 | 720/1200 | 0.40 it/sec | loss 1.8294[0m
[[36m02-28 21:19:07[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 2 | 960/1200 | 0.41 it/sec | loss 1.7760[0m
[[36m02-28 21:28:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 2 | loss=1.7378 | duration=2906.2390[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-28 21:29:41[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 2 | 29/146 | 0.32 it/sec | loss 1.5318[0m
[[36m02-28 21:31:12[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 2 | 58/146 | 0.32 it/sec | loss 1.5254[0m
[[36m02-28 21:32:42[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 2 | 87/146 | 0.32 it/sec | loss 1.5256[0m
[[36m02-28 21:34:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 2 | 116/146 | 0.33 it/sec | loss 1.5320[0m
[[36m02-28 21:35:36[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 2 | 145/146 | 0.33 it/sec | loss 1.5284[0m
[[36m02-28 21:35:37[0m][[34mbm.solver[0m][[32mINFO[0m] - [1mNew best valid loss 1.5284[0m
[[36m02-28 21:35:37[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 2 | loss=1.5284 | duration=453.2900[0m
[[36m02-28 21:36:13[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 9/45 | 0.31 it/sec[0m
[[36m02-28 21:36:39[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 18/45 | 0.33 it/sec[0m
[[36m02-28 21:37:02[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 27/45 | 0.35 it/sec[0m
[[36m02-28 21:37:27[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 36/45 | 0.35 it/sec[0m
[[36m02-28 21:38:19[0m][[34mbm.wer[0m][[32mINFO[0m] - wer 10000 negatives selected[0m
[[36m02-28 21:39:43[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 2254/11270 | 28.86 it/sec[0m
[[36m02-28 21:41:01[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 4508/11270 | 28.86 it/sec[0m
[[36m02-28 21:42:19[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 6762/11270 | 28.86 it/sec[0m
[[36m02-28 21:43:37[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 9016/11270 | 28.86 it/sec[0m
[[36m02-28 21:44:59[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTest Summary | Epoch 2 | wer=40.408% | wer_vocab=16.140% | duration=561.3918[0m
[[36m02-28 21:44:59[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-28 21:54:41[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 3 | 240/1200 | 0.42 it/sec | loss 1.4743[0m
[[36m02-28 22:06:22[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 3 | 480/1200 | 0.38 it/sec | loss 1.4350[0m
[[36m02-28 22:16:01[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 3 | 720/1200 | 0.39 it/sec | loss 1.4300[0m
[[36m02-28 22:25:27[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 3 | 960/1200 | 0.40 it/sec | loss 1.4073[0m
[[36m02-28 22:34:46[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 3 | loss=1.3885 | duration=2986.6706[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-28 22:36:09[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 3 | 29/146 | 0.38 it/sec | loss 1.5030[0m
[[36m02-28 22:37:25[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 3 | 58/146 | 0.38 it/sec | loss 1.4669[0m
[[36m02-28 22:38:40[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 3 | 87/146 | 0.38 it/sec | loss 1.4784[0m
[[36m02-28 22:39:55[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 3 | 116/146 | 0.38 it/sec | loss 1.4748[0m
[[36m02-28 22:41:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 3 | 145/146 | 0.39 it/sec | loss 1.4737[0m
[[36m02-28 22:41:06[0m][[34mbm.solver[0m][[32mINFO[0m] - [1mNew best valid loss 1.4737[0m
[[36m02-28 22:41:06[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 3 | loss=1.4737 | duration=379.2240[0m
[[36m02-28 22:41:37[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 9/45 | 0.36 it/sec[0m
[[36m02-28 22:41:58[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 18/45 | 0.39 it/sec[0m
[[36m02-28 22:42:19[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 27/45 | 0.40 it/sec[0m
[[36m02-28 22:42:40[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 36/45 | 0.41 it/sec[0m
[[36m02-28 22:43:35[0m][[34mbm.wer[0m][[32mINFO[0m] - wer 10000 negatives selected[0m
[[36m02-28 22:44:56[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 2254/11270 | 28.90 it/sec[0m
[[36m02-28 22:46:14[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 4508/11270 | 28.86 it/sec[0m
[[36m02-28 22:47:33[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 6762/11270 | 28.84 it/sec[0m
[[36m02-28 22:48:51[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 9016/11270 | 28.84 it/sec[0m
[[36m02-28 22:50:12[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTest Summary | Epoch 3 | wer=37.728% | wer_vocab=14.791% | duration=546.5166[0m
[[36m02-28 22:50:12[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-28 22:59:00[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 4 | 240/1200 | 0.46 it/sec | loss 1.1660[0m
[[36m02-28 23:07:24[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 4 | 480/1200 | 0.47 it/sec | loss 1.1724[0m
[[36m02-28 23:17:20[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 4 | 720/1200 | 0.44 it/sec | loss 1.1642[0m
[[36m02-28 23:27:16[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 4 | 960/1200 | 0.43 it/sec | loss 1.1495[0m
[[36m02-28 23:36:37[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 4 | loss=1.1467 | duration=2784.3194[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-28 23:38:14[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 4 | 29/146 | 0.32 it/sec | loss 1.4514[0m
[[36m02-28 23:40:29[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 4 | 58/146 | 0.26 it/sec | loss 1.4481[0m
[[36m02-28 23:43:11[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 4 | 87/146 | 0.23 it/sec | loss 1.4630[0m
[[36m02-28 23:45:51[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 4 | 116/146 | 0.21 it/sec | loss 1.4679[0m
[[36m02-28 23:48:20[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 4 | 145/146 | 0.21 it/sec | loss 1.4581[0m
[[36m02-28 23:48:22[0m][[34mbm.solver[0m][[32mINFO[0m] - [1mNew best valid loss 1.4581[0m
[[36m02-28 23:48:22[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 4 | loss=1.4581 | duration=704.1734[0m
[[36m02-28 23:49:25[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 9/45 | 0.18 it/sec[0m
[[36m02-28 23:50:11[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 18/45 | 0.18 it/sec[0m
[[36m02-28 23:50:58[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 27/45 | 0.19 it/sec[0m
[[36m02-28 23:51:44[0m][[34mbm.wer[0m][[32mINFO[0m] - WER | 36/45 | 0.19 it/sec[0m
[[36m02-28 23:53:11[0m][[34mbm.wer[0m][[32mINFO[0m] - wer 10000 negatives selected[0m
[[36m02-28 23:54:36[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 2254/11270 | 27.75 it/sec[0m
[[36m02-28 23:55:58[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 4508/11270 | 27.61 it/sec[0m
[[36m02-28 23:57:19[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 6762/11270 | 27.58 it/sec[0m
[[36m02-28 23:58:42[0m][[34mbm.wer[0m][[32mINFO[0m] - WER Rank | 9016/11270 | 27.56 it/sec[0m
[[36m02-29 00:00:10[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTest Summary | Epoch 4 | wer=36.646% | wer_vocab=14.836% | duration=708.2358[0m
[[36m02-29 00:00:10[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 00:12:00[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 5 | 240/1200 | 0.34 it/sec | loss 1.0141[0m
[[36m02-29 00:21:21[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 5 | 480/1200 | 0.38 it/sec | loss 1.0019[0m
[[36m02-29 00:30:26[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 5 | 720/1200 | 0.40 it/sec | loss 0.9870[0m
[[36m02-29 00:39:43[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 5 | 960/1200 | 0.41 it/sec | loss 0.9866[0m
[[36m02-29 00:48:53[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 5 | loss=0.9740 | duration=2921.9806[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 00:50:22[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 5 | 29/146 | 0.35 it/sec | loss 1.5592[0m
[[36m02-29 00:51:45[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 5 | 58/146 | 0.35 it/sec | loss 1.5248[0m
[[36m02-29 00:53:13[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 5 | 87/146 | 0.34 it/sec | loss 1.5061[0m
[[36m02-29 00:54:36[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 5 | 116/146 | 0.34 it/sec | loss 1.5057[0m
[[36m02-29 00:55:49[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 5 | 145/146 | 0.35 it/sec | loss 1.4974[0m
[[36m02-29 00:55:50[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 5 | loss=1.4974 | duration=416.7636[0m
[[36m02-29 00:55:50[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 01:05:27[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 6 | 240/1200 | 0.42 it/sec | loss 0.8423[0m
[[36m02-29 01:14:47[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 6 | 480/1200 | 0.42 it/sec | loss 0.8805[0m
[[36m02-29 01:23:55[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 6 | 720/1200 | 0.43 it/sec | loss 0.8776[0m
[[36m02-29 01:33:35[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 6 | 960/1200 | 0.43 it/sec | loss 0.8681[0m
[[36m02-29 01:43:34[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 6 | loss=0.8639 | duration=2862.6993[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 01:45:08[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 6 | 29/146 | 0.33 it/sec | loss 1.5586[0m
[[36m02-29 01:46:28[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 6 | 58/146 | 0.35 it/sec | loss 1.5646[0m
[[36m02-29 01:47:54[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 6 | 87/146 | 0.34 it/sec | loss 1.5628[0m
[[36m02-29 01:49:18[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 6 | 116/146 | 0.34 it/sec | loss 1.5679[0m
[[36m02-29 01:50:29[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 6 | 145/146 | 0.35 it/sec | loss 1.5535[0m
[[36m02-29 01:50:31[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 6 | loss=1.5535 | duration=416.9267[0m
[[36m02-29 01:50:31[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 02:00:06[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 7 | 240/1200 | 0.42 it/sec | loss 0.7909[0m
[[36m02-29 02:09:19[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 7 | 480/1200 | 0.43 it/sec | loss 0.7847[0m
[[36m02-29 02:18:32[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 7 | 720/1200 | 0.43 it/sec | loss 0.7722[0m
[[36m02-29 02:27:55[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 7 | 960/1200 | 0.43 it/sec | loss 0.7650[0m
[[36m02-29 02:37:09[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 7 | loss=0.7638 | duration=2796.8283[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 02:38:43[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 7 | 29/146 | 0.33 it/sec | loss 1.6355[0m
[[36m02-29 02:40:08[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 7 | 58/146 | 0.33 it/sec | loss 1.6113[0m
[[36m02-29 02:41:34[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 7 | 87/146 | 0.34 it/sec | loss 1.6257[0m
[[36m02-29 02:42:58[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 7 | 116/146 | 0.34 it/sec | loss 1.6388[0m
[[36m02-29 02:44:08[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 7 | 145/146 | 0.35 it/sec | loss 1.6353[0m
[[36m02-29 02:44:10[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 7 | loss=1.6353 | duration=420.9385[0m
[[36m02-29 02:44:10[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 02:53:32[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 8 | 240/1200 | 0.43 it/sec | loss 0.6841[0m
[[36m02-29 03:02:44[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 8 | 480/1200 | 0.43 it/sec | loss 0.6921[0m
[[36m02-29 03:12:10[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 8 | 720/1200 | 0.43 it/sec | loss 0.6919[0m
[[36m02-29 03:21:34[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 8 | 960/1200 | 0.43 it/sec | loss 0.6933[0m
[[36m02-29 03:30:53[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 8 | loss=0.6896 | duration=2803.0370[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 03:32:27[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 8 | 29/146 | 0.33 it/sec | loss 1.6983[0m
[[36m02-29 03:33:54[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 8 | 58/146 | 0.33 it/sec | loss 1.7099[0m
[[36m02-29 03:35:20[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 8 | 87/146 | 0.33 it/sec | loss 1.7231[0m
[[36m02-29 03:36:44[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 8 | 116/146 | 0.34 it/sec | loss 1.7142[0m
[[36m02-29 03:38:00[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 8 | 145/146 | 0.34 it/sec | loss 1.7138[0m
[[36m02-29 03:38:01[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 8 | loss=1.7138 | duration=427.8672[0m
[[36m02-29 03:38:01[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 03:47:38[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 9 | 240/1200 | 0.42 it/sec | loss 0.6108[0m
[[36m02-29 03:57:36[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 9 | 480/1200 | 0.41 it/sec | loss 0.6188[0m
[[36m02-29 04:07:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 9 | 720/1200 | 0.41 it/sec | loss 0.6249[0m
[[36m02-29 04:16:51[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 9 | 960/1200 | 0.41 it/sec | loss 0.6345[0m
[[36m02-29 04:26:36[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 9 | loss=0.6354 | duration=2913.7187[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 04:28:11[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 9 | 29/146 | 0.33 it/sec | loss 1.8964[0m
[[36m02-29 04:29:36[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 9 | 58/146 | 0.33 it/sec | loss 1.8999[0m
[[36m02-29 04:31:02[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 9 | 87/146 | 0.34 it/sec | loss 1.8978[0m
[[36m02-29 04:32:27[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 9 | 116/146 | 0.34 it/sec | loss 1.8820[0m
[[36m02-29 04:33:40[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 9 | 145/146 | 0.35 it/sec | loss 1.8836[0m
[[36m02-29 04:33:41[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 9 | loss=1.8836 | duration=425.4440[0m
[[36m02-29 04:33:41[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 04:43:05[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 10 | 240/1200 | 0.43 it/sec | loss 0.5910[0m
[[36m02-29 04:52:14[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 10 | 480/1200 | 0.43 it/sec | loss 1.6838[0m
[[36m02-29 05:01:22[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 10 | 720/1200 | 0.44 it/sec | loss 1.3788[0m
[[36m02-29 05:10:31[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 10 | 960/1200 | 0.44 it/sec | loss 1.1989[0m
[[36m02-29 05:19:31[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 10 | loss=1.0800 | duration=2748.4324[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 05:21:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 10 | 29/146 | 0.34 it/sec | loss 1.6201[0m
[[36m02-29 05:22:35[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 10 | 58/146 | 0.33 it/sec | loss 1.6691[0m
[[36m02-29 05:24:03[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 10 | 87/146 | 0.33 it/sec | loss 1.6731[0m
[[36m02-29 05:25:30[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 10 | 116/146 | 0.33 it/sec | loss 1.6774[0m
[[36m02-29 05:26:50[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 10 | 145/146 | 0.34 it/sec | loss 1.6702[0m
[[36m02-29 05:26:51[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 10 | loss=1.6702 | duration=440.3874[0m
[[36m02-29 05:26:51[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 05:36:15[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 11 | 240/1200 | 0.43 it/sec | loss 0.5582[0m
[[36m02-29 05:45:29[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 11 | 480/1200 | 0.43 it/sec | loss 0.5578[0m
[[36m02-29 05:54:33[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 11 | 720/1200 | 0.44 it/sec | loss 0.5545[0m
[[36m02-29 06:03:57[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 11 | 960/1200 | 0.43 it/sec | loss 0.5481[0m
[[36m02-29 06:13:06[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 11 | loss=0.5497 | duration=2773.5201[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 06:14:40[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 11 | 29/146 | 0.33 it/sec | loss 1.7810[0m
[[36m02-29 06:16:04[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 11 | 58/146 | 0.34 it/sec | loss 1.8064[0m
[[36m02-29 06:17:28[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 11 | 87/146 | 0.34 it/sec | loss 1.7796[0m
[[36m02-29 06:18:51[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 11 | 116/146 | 0.34 it/sec | loss 1.7740[0m
[[36m02-29 06:20:07[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 11 | 145/146 | 0.35 it/sec | loss 1.7787[0m
[[36m02-29 06:20:08[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 11 | loss=1.7787 | duration=422.3254[0m
[[36m02-29 06:20:08[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 06:29:37[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 12 | 240/1200 | 0.43 it/sec | loss 0.4998[0m
[[36m02-29 06:38:58[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 12 | 480/1200 | 0.43 it/sec | loss 0.5232[0m
[[36m02-29 06:48:09[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 12 | 720/1200 | 0.43 it/sec | loss 0.5233[0m
[[36m02-29 06:57:16[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 12 | 960/1200 | 0.43 it/sec | loss 0.5248[0m
[[36m02-29 07:06:23[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 12 | loss=0.5269 | duration=2773.7050[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 07:07:59[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 12 | 29/146 | 0.33 it/sec | loss 1.8047[0m
[[36m02-29 07:09:18[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 12 | 58/146 | 0.34 it/sec | loss 1.8193[0m
[[36m02-29 07:10:34[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 12 | 87/146 | 0.36 it/sec | loss 1.8094[0m
[[36m02-29 07:11:50[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 12 | 116/146 | 0.36 it/sec | loss 1.8167[0m
[[36m02-29 07:12:57[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 12 | 145/146 | 0.37 it/sec | loss 1.8121[0m
[[36m02-29 07:12:58[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 12 | loss=1.8121 | duration=394.6722[0m
[[36m02-29 07:12:58[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 07:21:42[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 13 | 240/1200 | 0.46 it/sec | loss 0.5195[0m
[[36m02-29 07:30:10[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 13 | 480/1200 | 0.47 it/sec | loss 0.5238[0m
[[36m02-29 07:38:30[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 13 | 720/1200 | 0.47 it/sec | loss 0.5231[0m
[[36m02-29 07:46:56[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 13 | 960/1200 | 0.47 it/sec | loss 0.5262[0m
[[36m02-29 07:55:10[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 13 | loss=0.5276 | duration=2530.9441[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
[[36m02-29 07:56:33[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 13 | 29/146 | 0.38 it/sec | loss 1.8448[0m
[[36m02-29 07:57:51[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 13 | 58/146 | 0.38 it/sec | loss 1.8453[0m
[[36m02-29 07:59:07[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 13 | 87/146 | 0.38 it/sec | loss 1.8444[0m
[[36m02-29 08:00:25[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 13 | 116/146 | 0.38 it/sec | loss 1.8574[0m
[[36m02-29 08:01:29[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 13 | 145/146 | 0.39 it/sec | loss 1.8538[0m
[[36m02-29 08:01:30[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 13 | loss=1.8538 | duration=380.0713[0m
[[36m02-29 08:01:30[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
[[36m02-29 08:09:41[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 14 | 240/1200 | 0.50 it/sec | loss 0.5064[0m
[[36m02-29 08:17:34[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 14 | 480/1200 | 0.50 it/sec | loss 0.5163[0m
[[36m02-29 08:25:26[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 14 | 720/1200 | 0.50 it/sec | loss 0.5146[0m
[[36m02-29 08:33:19[0m][[34mflashy.solver[0m][[32mINFO[0m] - Train | Epoch 14 | 960/1200 | 0.50 it/sec | loss 0.5138[0m
[[36m02-29 08:40:50[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mTrain Summary | Epoch 14 | loss=0.5209 | duration=2358.9795[0m
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f0b1401dc10>
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1478, in __del__
    self._shutdown_workers()
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1461, in _shutdown_workers
    if w.is_alive():
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
AssertionError: can only test a child process
Traceback (most recent call last):
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/zubrikhina/anaconda3/envs/bm/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
[[36m02-29 08:42:07[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 14 | 29/146 | 0.41 it/sec | loss 2.0264[0m
[[36m02-29 08:43:16[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 14 | 58/146 | 0.41 it/sec | loss 2.0299[0m
[[36m02-29 08:44:25[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 14 | 87/146 | 0.42 it/sec | loss 2.0464[0m
[[36m02-29 08:45:34[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 14 | 116/146 | 0.42 it/sec | loss 2.0331[0m
[[36m02-29 08:46:38[0m][[34mflashy.solver[0m][[32mINFO[0m] - Valid | Epoch 14 | 145/146 | 0.42 it/sec | loss 2.0031[0m
[[36m02-29 08:46:39[0m][[34mflashy.solver[0m][[32mINFO[0m] - [1mValid Summary | Epoch 14 | loss=2.0031 | duration=349.0119[0m
[[36m02-29 08:46:39[0m][[34mbm.solver[0m][[33mWARNING[0m] - Model valid_loss did not improve for 10 epochs. Stopping the training.[0m
[[36m02-29 08:46:39[0m][[34mbm.solver[0m][[32mINFO[0m] - Scale Reject | Ratio 0.000%[0m
wandb: - 0.015 MB of 0.015 MB uploadedwandb: WARNING No program path found, not creating job artifact. See https://docs.wandb.ai/guides/launch/create-job
wandb: \ 0.015 MB of 0.015 MB uploadedwandb: | 0.015 MB of 0.052 MB uploadedwandb: / 0.052 MB of 0.052 MB uploadedwandb: 
wandb: Run history:
wandb:  test/duration ▃▂▁█
wandb:       test/wer █▃▂▁
wandb: test/wer_vocab █▂▁▁
wandb: train/duration █▄▄▃▄▃▃▃▄▃▃▃▂▁
wandb:     train/loss █▄▃▂▂▂▂▁▁▂▁▁▁▁
wandb: valid/duration ▄▃▂█▂▂▂▃▃▃▂▂▂▁
wandb:     valid/loss ▆▂▁▁▂▂▃▄▆▄▅▆▆█
wandb: 
wandb: Run summary:
wandb:  test/duration 708.23582
wandb:       test/wer 0.36646
wandb: test/wer_vocab 0.14836
wandb: train/duration 2358.97948
wandb:     train/loss 0.52086
wandb: valid/duration 349.01188
wandb:     valid/loss 2.0031
wandb: 
wandb: 🚀 View run c97c100b at: https://wandb.ai/gnn-neuro/brainmagick/runs/c97c100b
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240228_191732-c97c100b/logs
